### ISSUE TITLE
领积分页面有更新

### ISSUE THREAD

**Issue by Ehustein** [TonyJiangWJ/Alipay-Credits#1]
"未找到目标"，不知道是不是我的问题，以前也有遇到过但是过几天自己又好了

**Comment by williamglasgow** [comment]
确实是更新了，“点击领取”按钮改了。
另外我个人用着这个一直有点点问题，就是不管积分有几份，每次必点两次领积分，两份以上的话就会漏领。只有一份的话就会误点到别的界面（积分任务什么的），而导致进不去家庭积分领取页面了。不过之前我一天设置三个时间领积分，基本能解决漏领问题。
提出供作者参考。

**Comment by TonyJiangWJ** [comment]
已更新

**Comment by williamglasgow** [comment]
使用了两天，没发现任何问题，运行完美！
