### ISSUE TITLE
无法识别家庭积分球

### ISSUE THREAD

**Issue by williamglasgow** [TonyJiangWJ/Alipay-Credits#3]
可以进入家庭积分页面，但无法识别红色的家庭积分球。提示无积分可领取

**Comment by TonyJiangWJ** [comment]
自行修改一下代码吧  最近没时间更新，`core/CreditRunner.js`  line: 91 `成员管理` 改成 `家庭积分`
```javascript
      if (widgetUtils.widgetWaiting(".*家庭积分.*")) {
```

**Comment by williamglasgow** [comment]
大佬辛苦。改了以后这个问题没了。
又发现另一个问题就是，运行代码的时候如果没有普通积分，那么就会跳转到 好物时刻 这个怎么修改解决啊

**Comment by TonyJiangWJ** [comment]
87行的sleep加长一些试试，加到3000看看吧

**Comment by williamglasgow** [comment]
哈哈看起来没问题了，不会跳到好物时刻了，感谢大佬！
