### ISSUE TITLE
领不到家庭积分

### ISSUE THREAD

**Issue by williamglasgow** [TonyJiangWJ/Alipay-Credits#6]
每次领完普通积分以后下半部分上移，然后家庭积分判断位置就会错，上次更新之前点进错的位置会退出来再找一遍家庭积分，上次更新之后在错的位置一直找不到家庭积分控件然后等半天就判断领取完毕退出了？
是我哪里没设置对还是除了其他问题呢？
查找控件超时设置的是1s
检测控件是否存在超时设置了8s
获取截图等待时间设置的是0.5s

**Comment by TonyJiangWJ** [comment]
这个暂时没办法，之前的是可以点到错误页面，然后返回重新刷新控件信息，现在的不行了。
需要重新修改寻找逻辑。目前只能领取会员积分

**Comment by williamglasgow** [comment]
好吧，我还以为是我设置有问题呢。坐等大佬改进嘿嘿

**Comment by TonyJiangWJ** [comment]
已更新新版
